### GET request to FastAPI server
GET http://localhost:8000

### Create session
POST http://localhost:8000/session

### Switch model
POST http://localhost:8000/model?model=openai

### Send a form with the text and file fields
POST http://localhost:8000/data/input?token=abc
Content-Type: multipart/form-data; boundary=boundary

#--WebAppBoundary
#Content-Disposition: form-data; name="element-name"
#Content-Type: text/plain
#
#Name
--boundary
Content-Disposition: form-data; name="files"; filename="data.csv"
Content-Type: text/csv

< ./data/titanic.csv
--boundary
Content-Disposition: form-data; name="files"; filename="data.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./data/titanic.xlsx
--FileBoundary--
--boundary--
